/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ChatClient;

import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPasswordField;
import ChatClient.SignupAccount;

/**
 *
 * @author vhg
 */
public class SignupWindowForm extends javax.swing.JFrame {

//    public String File = "src/ChatClient/UserAccount.txt";
    public ArrayList userAccount;
    private String username = "";
    private String password = "";
    private String comfirmPassword = "";
    private boolean check = false, check2 = false, check3 = false;

    /**
     * Creates new form SignupWindowForm
     */
    public void customForm() {

        Color btnSignupColor = new Color(204, 0, 51);
        btnSignup.setBackground(btnSignupColor);

        tfUsername.setFocusable(false);
        tfPassword.setFocusable(false);
        tfComfirmPassword.setFocusable(false);

        // set the echo character of the password field 
        tfPassword.setEchoChar((char) 0);
        tfPassword.setForeground(Color.LIGHT_GRAY);
        // set initial text for password field 
        tfPassword.setText("Password");

        tfComfirmPassword.setEchoChar((char) 0);
        tfComfirmPassword.setForeground(Color.LIGHT_GRAY);
        tfComfirmPassword.setText("Comfirm password");
        lblErrorSignup.setText("");
        userAccount = new ArrayList();
    }

    public SignupWindowForm() {
        initComponents();
        customForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        tfUsername = new javax.swing.JTextField();
        tfComfirmPassword = new javax.swing.JPasswordField();
        tfPassword = new javax.swing.JPasswordField();
        btnSignup = new javax.swing.JButton();
        lblErrorSignup = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");
        jMenuItem1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));

        tfUsername.setForeground(new java.awt.Color(204, 204, 204));
        tfUsername.setText("Username");
        tfUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfUsernameMouseClicked(evt);
            }
        });
        tfUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUsernameActionPerformed(evt);
            }
        });

        tfComfirmPassword.setText("jPasswordField1");
        tfComfirmPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfComfirmPasswordMouseClicked(evt);
            }
        });
        tfComfirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfComfirmPasswordActionPerformed(evt);
            }
        });

        tfPassword.setText("jPasswordField1");
        tfPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfPasswordMouseClicked(evt);
            }
        });

        btnSignup.setBackground(new java.awt.Color(255, 204, 0));
        btnSignup.setForeground(new java.awt.Color(255, 255, 255));
        btnSignup.setText("Sign up");
        btnSignup.setBorder(null);
        btnSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignupActionPerformed(evt);
            }
        });

        lblErrorSignup.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblErrorSignup.setForeground(new java.awt.Color(204, 0, 51));
        lblErrorSignup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblErrorSignup.setText("jLabel1");

        jLabel1.setFont(new java.awt.Font("Segoe Script", 1, 31)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MAETAMONG");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(342, 342, 342)
                        .addComponent(btnSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblErrorSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfUsername)
                                .addComponent(tfComfirmPassword)
                                .addComponent(tfPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(203, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfComfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btnSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblErrorSignup)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUsernameActionPerformed

    private void tfUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfUsernameMouseClicked
        // TODO add your handling code here:
        check = true;
        tfUsername.setText("");
        tfUsername.setForeground(Color.BLACK);
        tfUsername.setFocusable(true);
    }//GEN-LAST:event_tfUsernameMouseClicked

    private void btnSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignupActionPerformed
        // TODO add your handling code here:
        if (check && check2 && check3) {
            username = tfUsername.getText().toString();
            password = changePassword(tfPassword);
            comfirmPassword = changePassword(tfComfirmPassword);
        } else {
            username = "";
            password = "";
            comfirmPassword = "";
        }

        if (password == "" || comfirmPassword == "" || username == "") {
            lblErrorSignup.setText("Fill your information");
            tfUsername.setText("");
            tfUsername.requestFocus();
            tfPassword.requestFocus();
            tfComfirmPassword.requestFocus();
            tfUsername.setFocusable(true);
        } else {
            if (password.equals(comfirmPassword) == false) {
                lblErrorSignup.setText("Incorrect password");
            } else {

                SignupAccount sg = new SignupAccount(username, password);
                userAccount.add(sg);
                ReadFile rf = new ReadFile();
                rf.writeFile(sg);

                this.setVisible(false);
                new LoginWindowForm().setVisible(true);
            }
        }
    }//GEN-LAST:event_btnSignupActionPerformed

    private void tfPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfPasswordMouseClicked
        // TODO add your handling code here:
        check2 = true;
        tfPassword.setText("");
        tfPassword.setForeground(Color.BLACK);
        tfPassword.setFocusable(true);
        tfPassword.setEchoChar('*');
    }//GEN-LAST:event_tfPasswordMouseClicked

    private void tfComfirmPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfComfirmPasswordMouseClicked
        // TODO add your handling code here:
        check3 = true;
        tfComfirmPassword.setText("");
        tfComfirmPassword.setForeground(Color.BLACK);
        tfComfirmPassword.setFocusable(true);
        tfComfirmPassword.setEchoChar('*');
    }//GEN-LAST:event_tfComfirmPasswordMouseClicked

    private void tfComfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfComfirmPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfComfirmPasswordActionPerformed

    public String changePassword(JPasswordField passField) {
        char[] p = passField.getPassword();
        String pass = "";
        for (Character c : p) {
            pass += c.toString();
        }
        return pass;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignupWindowForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignupWindowForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignupWindowForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignupWindowForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignupWindowForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSignup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblErrorSignup;
    private javax.swing.JPasswordField tfComfirmPassword;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
